pipeline:
  s3_upload:
    image: anigeo/awscli
    environment:
        - AWS_CONFIG_FILE=.drone_aws_config
    commands:
        - aws s3 cp test.txt s3://df.s3.datafabric-poc.node1/test.txt
    when:
        branch: master
        event: push
    write_external_id:
        image: busybox
        commands:
            - echo "external_id = $${EXTERNAL_ID}" >> .drone_aws_config
        secrets:
            - external_id