FROM golang:alpine

LABEL team="datafabric"
LABEL description="go infrastructure module for aws go sdk"

RUN apk update && apk add --no-cache git

RUN apk add --update \
    python3 \
    python3-dev \
    py3-pip \
    openssh \
    build-base

COPY . $GOPATH/src/mg/datafabric/app/

WORKDIR $GOPATH/src/mg/datafabric/app/

RUN go get -d -v github.com/aws/aws-sdk-go

RUN git clone https://github.com/awsdocs/aws-doc-sdk-examples

RUN go build aws-doc-sdk-examples/go/example_code/s3/list_all_buckets.go

ENTRYPOINT sh
